// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.0.0"
#define MICROPY_GIT_HASH "s"
#define MICROPY_BUILD_DATE "2020-09-29"
#define MICROPY_VERSION_MAJOR (1)
#define MICROPY_VERSION_MINOR (9)
#define MICROPY_VERSION_MICRO (2)
#define MICROPY_VERSION_STRING "1.0.0"
